
services:
  netbox:
    image: netboxcommunity/netbox:v3.7
    container_name: netbox
    restart: unless-stopped
    env_file: ./netbox.env
    depends_on:
      - postgres
      - redis
    ports:
      - "8000:8080"
    volumes:
      - netbox-media:/opt/netbox/netbox/media
      - netbox-reports:/opt/netbox/netbox/reports
      - netbox-scripts:/opt/netbox/netbox/scripts
    networks:
      - netbox-net

  postgres:
    image: postgres:15
    container_name: netbox-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: netbox
      POSTGRES_PASSWORD: Paradoxes4u2know
      POSTGRES_DB: netbox
    volumes:
      - netbox-postgres-data:/var/lib/postgresql/data
    networks:
      - netbox-net

  redis:
    image: redis:7
    container_name: netbox-redis
    restart: unless-stopped
    command: ["redis-server", "--requirepass", "your_redis_password"]
    volumes:
      - netbox-redis-data:/data
    networks:
      - netbox-net

volumes:
  netbox-media:
  netbox-reports:
  netbox-scripts:
  netbox-postgres-data:
  netbox-redis-data:

networks:
  netbox-net:
    driver: bridge
